import React, { useState, useEffect } from "react"
import Head from 'next/head'
import { motion, useMotionValue, useTransform } from "framer-motion"
import styles from '../styles/Welcome.module.scss'
import stylesClickMe from '../styles/global/ClickMe.module.scss'
import Link from "next/link";

const Welcome = () => {
  const x = useMotionValue(445)
  const y = useMotionValue(445)

  const rotateY = useTransform(x, [0, 1024], [-20, 20])
  const rotateX = useTransform(y, [0, 1000], [20, -20])

  function handleMouse(event) {
    x.set(event.pageX)
    y.set(event.pageY)
  }

  const textVariants = {
    hidden: {
      y: 20, opacity: 0
    },
    visible: {
      y: 0, opacity: 1
    }
  }

  const cursorMotion = {
    rest: { 
      transform: "translate(-50%, -50%) scale(0)",
      ease: "easeOut", 
      duration: 0.2, 
      type: "tween" 
    },
    hover: {
      transform: "translate(-50%, -50%) scale(1)",
      transition: {
        duration: 0.4,
        type: "tween",
        ease: "easeIn"
      }
    }
  }

  const strokeVariants = {
    hidden: { 
      height: 0,
    },
    visible: {
      height: "40vh",
    }
  }

  return (
    <div>
      <Head>
        <title>eMJi - Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.hero}>
        <motion.div
          variants={strokeVariants}
          initial="hidden"
          animate="visible"
          transition={{
            duration: 1, ease: "easeInOut",
          }}
          className={styles.line}
        />
      </div>
      
      <div className={styles.article}>
        <motion.article 
          initial="rest" 
          whileHover="hover" 
          animate="rest"

          onMouseMove={handleMouse} 
          style={{
            display: "inline-block",
            // rotateY: rotateY,
            // rotateX: rotateX,
          }}>

          <motion.div
            variants={cursorMotion}
            className={stylesClickMe.clickMe}
            style={{
              top: y,
              left: x,
            }}
          >
          <Link href="/home">
            <p>Click me</p>
          </Link>
          </motion.div>

          <motion.h1
            variants={textVariants}
            initial="hidden"
            animate="visible"
            transition={{ 
              duration: 1,
              delay: .5
            }}>
              Hello !
          </motion.h1>

          <motion.h1
            variants={textVariants}
            initial="hidden"
            animate="visible"
            transition={{ 
              duration: 1,
              delay: 1
            }}>
              My name is
          </motion.h1>

          <motion.h1
            variants={textVariants}
            initial="hidden"
            animate="visible"
            transition={{ 
              duration: 1,
              delay: 1.5
            }}>
              Matondo Julien
          </motion.h1>
        </motion.article>

        <motion.figure
          variants={textVariants}
          initial="hidden"
          animate="visible"
          transition={{ 
            duration: 1,
            delay: 2
          }}>
          <p>Behance</p>
          <p>Facebook</p>
          <p>Twitter</p>
        </motion.figure>
      </div>
    </div>
  )
}

export default Welcome
